---
language: ruby
script: "bundle exec rake validate && bundle exec rake lint"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="4.2.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="4.8.0" STRICT_VARIABLES="yes"
notifications:
  email: false
